import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from '../comps/NavBar'
import Intro from '../comps/Intro'
import Marquee from '../comps/Marquee'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main className={styles.main}>
        <NavBar/>

        <div style={{display:'flex', flexDirection:'row', marginTop:''}}>
        <Intro/>
        <Marquee/>
        </div>

        
    </main>

    </div>
  )
}
